### ISSUE TITLE
Help in code

### ISSUE THREAD

**Issue by Hongjun1108** [BlackTea12/differential_drive_2wheels#1]
Hi, I have a question when I run your code "[DifferentialDriveMain.m](https://github.com/BlackTea12/differential_drive_2wheels/blob/main/Matlab/DifferentialDriveMain.m)", I find it is not convergent. It will be a great help to me if you can answer this question. Thanks in advance.

**Comment by BlackTea12** [comment]
First, I'm sorry to say that the codes I have uploaded are not fully available. Only the code I've mentioned in the README.md ('[DifferentialDriveSMCModel.slxc](https://github.com/BlackTea12/differential_drive_2wheels/blob/main/Matlab/DifferentialDriveSMCModel.slxc)' and '[mpc_main.m](https://github.com/BlackTea12/differential_drive_2wheels/blob/main/Matlab/mpc_main.m)' are executable. Other codes, you can think it is a uncompleted sketches. 
For the problem that you've mentioned, the controller that is designed into the code is rather simple. It is only a position controller, so even if the vehicle is near the goal point, it cannot exactly(as we expect it to be) decrease its velocity because there is no velocity controller. Although, if you get the exact tuning parameter for the right reference value, then you might be able to decrease its velocity and both arrive at the goal point. However, I haven't put multiple controllers in the code.
I don't know if my answers solved your question but hope it helps! If you have any question, please let me know. (:

**Comment by Hongjun1108** [comment]
Thank you for your kind and prompt response. Since I am unfamiliar with this field, I will find some references to help me understand your work. Anyhow, many thanks for your help.
